# Generated by Django 3.0.5 on 2020-04-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producent', models.CharField(max_length=32)),
                ('szerokosc', models.PositiveSmallIntegerField(default=0)),
                ('profil', models.PositiveSmallIntegerField(default=0)),
                ('srednica', models.PositiveSmallIntegerField(default=0)),
                ('opis', models.TextField(blank=True, default='')),
                ('rok_produkcji', models.DateField(default=2000)),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='zdjecia')),
            ],
        ),
    ]
