# Generated by Django 3.0.7 on 2020-06-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wulkanizacjaweb', '0002_koszyk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opony',
            name='zdjecie',
            field=models.ImageField(blank=True, null=True, upload_to='plakaty'),
        ),
    ]
