# Generated by Django 3.0.7 on 2020-06-09 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wulkanizacjaweb', '0003_auto_20200609_2257'),
        ('wulkanizacjaweb', '0003_auto_20200609_2256'),
    ]

    operations = [
    ]
