# Generated by Django 3.0.7 on 2020-06-09 23:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wulkanizacjaweb', '0004_merge_20200609_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='opony',
            name='modelnazwa',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
